# MedicaoController Tests

### Pegar uma medicao específica
GET http://localhost:8080/api/dia/2024-05-21/hora/00/medicao/1

### Pegar todas as medições de um dia
GET http://localhost:8080/api/dia/2024-05-21

### Pegar todas as medições de uma hora
GET http://localhost:8080/api/dia/2024-05-21/hora/00

### Enviar uma medição
POST http://localhost:8080/api/medicao
Content-Type: application/json

{
  "idEstacao": "ESTLABPENSO001",
  "timestamp": "2024-05-21T00:50:00",
  "temperatura": 27.5,
  "umidade": 50.0,
  "percentualUV": 70.0,
  "nivelUV": 6.5,
  "pressao": 1013.25,
  "luminosidade": 5500.0,
  "mlChuva": 0.0
}

### Excluir medição por ID
DELETE http://localhost:8080/api/medicao/1
